### ISSUE TITLE
ValueError test.py with level TRACE

### ISSUE THREAD

**Issue by DanielDugan** [tl-its-umich-edu/api-utils-python#11]
ng/__init__.py", line 182, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'TRACE'

Worked around by commenting out. 
#logging.basicConfig(level="TRACE")
I will take some time and review **logging**

**Comment by jonespm** [comment]
Hmm, this is brought in from [autologging.](https://pypi.org/project/Autologging/)

`TRACE The autologging.TRACE (level 1) log level is registered with the Python logging module when Autologging is imported so that tracing can be configured and controlled independently of application logging.
`

Maybe I have to import autologging here too.
